print ("                -")
print ("    4       -       -       3")
print ("        -               -")
print ("    -                       -")
print ("-               5               -")
print ("|   -                       -   |")
print ("|       -               -       |")
print ("|           -       -           |")
print ("|               -               |")
print ("|               |               |")
print ("|       1       |       2       |")
print ("|               |               |")
print ("-               |               -")
print ("    -           |           -")
print ("        -       |       -")
print ("            -   |   -")
print ("                -")
print ("                0")
